export { default as Home } from "./Home"
export { default as About } from "./About"
export { default as Resume } from "./Resume"
export { default as Courses } from "./Courses"
export { default as Comments } from "./Comments"
export { default as Contact } from "./Contact"